### ISSUE TITLE
script doesn't work

### ISSUE THREAD

**Issue by tazihad** [mirkobrombin/itchio-bottles-setup#1]
bottles version: 2022.10.14.1

**Comment by mirkobrombin** [comment]
what's the output?

**Comment by tazihad** [comment]
@mirkobrombin script runs successfully. But games doesn't play.

**Comment by mirkobrombin** [comment]
Does itchio let you install the game?

**Comment by tazihad** [comment]
@mirkobrombin yes. I can install games. I have also install bunch of dependency. I can play same game by manually adding exe in bottle. But I can't play from itch io app. It crashes without any error. Game doesn't launch.
